### PR TITLE
Add Django 1.11 support

### PR DESCRIPTION
**Pull request by un-def**
This PR closes https://github.com/django-polymorphic/django-polymorphic/issues/267 issue.

### CODE REVIEW

**Comment by un-def** [comment]
Sorry, I overlooked https://github.com/django-polymorphic/django-polymorphic/pull/276
My solution is almost identical.

**Comment by vdboor** [comment]
Hi! thanks for this work! This helped me a great deal. After merging #276 I've also merged your changes as they handle the chunking better.

**Comment by jleclanche** [comment]
Yay :) eta on a release?

**Comment by vdboor** [comment]
FYI, this version was released the may 1st

**Pull request merged**
