### PR TITLE
Swapped polymorphic models don't work on Django>=1.10

### PR DESCRIPTION
**Pull request by skirsdeda**
This is so because polymorphic tries to validate manager on a swapped model while such manager is inaccessible (described in detail in #270)

### CODE REVIEW

**Comment by skirsdeda** [comment]
Test on Django 1.10 and 1.11 have failed as expected.

**Comment by skirsdeda** [comment]
And with the fix the new tests pass :)

**Comment by hvdklauw** [comment]
Hmm kinda sad that this fix is only in the 2.0 release which doesn't support django 1.10, while this issue is very much present in 1.10, now I'll have to skip a whole test step in my path to upgrade a project from django 1.8 to 1.11 because there is no version that works

**Comment by vdboor** [comment]
@hvdklauw @skirsdeda  django-polymorphic 1.3.1 is released with these changes included. Since I got more of these requests,  @skirsdeda inspired me to do a 1.3.1 release. It contains almost all bugfixes from the 2.0 release

**Comment by skirsdeda** [comment]
@vdboor Great!

**Pull request merged**
