### PR TITLE
Run CI with postgres too

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Travis seems to have given up building my branch, so opening a PR early for that. Feedback is also welcome though.

Note: I'll rebase this once it works as expected.

Update: Closes #282

### CODE REVIEW

**Comment by meshy** [comment]
This is related to https://github.com/django-polymorphic/django-polymorphic/pull/282 (although my branch is out of date with `master`.

**Comment by hobarrera** [comment]
Darn. It's running fine now, but the tests themselves are failing due to [apparently] a migration not being run on time.

I'd appreciate some feedback on the current failures.

**Comment by meshy** [comment]
It's possible you're having the same issues I had when running migrations... have you seen this commit on my branch? https://github.com/django-polymorphic/django-polymorphic/pull/282/commits/e641e14e2b0c1e93f1a4b653f19eb1ce54a5038f

**Comment by hobarrera** [comment]
Damn, I hadn't, and you were a minute too late!

Yup, same issue with migrations, apparently.

**Comment by meshy** [comment]
Sorry about that -- I was just typing as I saw your commit come in!

**Comment by hobarrera** [comment]
Rebased and squashed. This latest pull should be ready to merge. 🎉

**Comment by hobarrera** [comment]
Note for reviewers: The diff might look huge, but: `polymorphic/tests/models.py` is basically a cut+paste of `polymorphic/tests/__init__.py`. This was required due to how django loads models, which I needed to create the migrations.

`polymorphic/tests/migrations/0001_initial.py` is used to create models during tests -- syncdb won't work because of migration (foreign key) dependencies. This didn't matter with sqlite. No need to review this file since it's the auto-generated migration.

**Comment by hobarrera** [comment]
Bump? 🙂

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by vdboor** [comment]
You're welcome! Thanks for the work on this!

**Pull request merged**
