### PR TITLE
changes made to support djnago 2.2

### PR DESCRIPTION
**Pull request by auvipy**
work in progress, should django 1.11 support dropped?

### CODE REVIEW

**Comment by auvipy** [comment]
what to do to fix     raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.8.2).

**Comment by auvipy** [comment]
install libsqlite3-dev libsqlite3 this or update Tarvis os ubuntu version?

**Comment by auvipy** [comment]
only one eror in 2.x version, python34 n 35 need trusty dist AFAIK.
django-polymorphic/polymorphic/formsets/utils.py", line 15, in add_media
    dest._css = combined._css
AttributeError: can't set attribute

**Comment by pod2metra** [comment]
the reason is that _css and _js are properties now. You may change add_media function and add flow for Django 2.2 version. 

```
"""
Internal utils
"""
import django


def add_media(dest, media):
    """
    Optimized version of django.forms.Media.__add__() that doesn't create new objects.

    Only required for Django < 2.0
    """
    if django.VERSION >= (2, 2):
        dest._css_lists.extend(media._css_lists)
        dest._js_lists.extend(media._js_lists)
    elif django.VERSION >= (2, 0):
        combined = dest + media
        dest._css = combined._css
        dest._js = combined._js
    else:
        dest.add_css(media._css)
        dest.add_js(media._js)
```

**Comment by auvipy** [comment]
thank you for the solution, going to push it.

**Comment by auvipy** [comment]
resume work this week end

**Comment by auvipy** [comment]
@vdboor

**Comment by ShaheedHaque** [comment]
Any chance of a PyPi release with this support for Django 2.2 and #370 please?

**Comment by hidaris** [comment]
@vdboor ping

**Comment by mkjpryor-stfc** [comment]
What can we do to speed this up? This is a blocker for me at the moment.

**Comment by auvipy** [comment]
this pr is good to go as is except 1 style issue which is minor

**Comment by wfehr** [comment]
Any news here? Would love to use django-polymorphic with django2.2 :)

**Comment by SteveGZr** [comment]
bump!

**Comment by dgorobets** [comment]
bump

**Comment by vdboor** [comment]
Sorry for the late action, I've squash-merged this in 26fac56e315def54918e383aba31b2110fdc8828

**Comment by auvipy** [comment]
you should have give the contributor credit by using git co-author. twice I tried to contribute you merged both in your name

**Pull request closed without merging**
